apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sec-dasloader.fullname" . }}
  labels:
    {{- include "sec-dasloader.labels" . | nindent 4 }}
data:
  MONGODB_USER: '{{ .Values.global.db.MONGO_INITDB_ROOT_USERNAME }}'
  MONGODB_PASSWORD: '{{ .Values.global.db.MONGO_INITDB_ROOT_PASSWORD }}'
  MONGODB_HOST: '{{ .Values.global.db.MONGO_INITDB_HOST_RESTRICTED }}'
  MONGODB_USER_ADMIN: '{{ .Values.global.db.MONGO_INITDB_ROOT_USERNAME }}'
  MONGODB_PASSWORD_ADMIN: '{{.Values.global.db.MONGO_INITDB_ROOT_PASSWORD }}'
  MONGODB_DBNAME: '{{ .Values.global.db.MONGO_INITDB_DATABASE_NEW }}'
  AWS_BUCKET: '{{ .Values.global.AWS.BUCKET_NAME_NASA }}'
  AWS_ACCESS_KEY_ID: '{{ .Values.global.AWS.SECRET_ID_NASA }}'
  AWS_SECRET_ACCESS_KEY: '{{ .Values.global.AWS.SECRET_KEY_NASA }}'
  AWS_S3_ENDPOINT: '{{ .Values.global.AWS.ENDPOINT_NASA }}'
  WCSPATH_ENDPOINT: '{{ .Values.config.WCSPATH_ENDPOINT }}'
  INGESTION_LOG: '{{ .Values.config.INGESTION_LOG }}'
  TMP_VRT_DIR: '{{.Values.config.TMP_VRT_DIR }}'
  GDAL_DISABLE_READDIR_ON_OPEN : "EMPTY_DIR"
