apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mwcs.fullname" . }}
  labels:
    {{- include "mwcs.labels" . | nindent 4 }}
data:
  MWCS_MAX_MEMORY          : "{{ .Values.global.MWCS.MEMORY }}"
  AWS_SECRET_ID            : "{{ .Values.global.AWS.SECRET_ID }}"
  AWS_SECRET_KEY           : "{{ .Values.global.AWS.SECRET_KEY }}"
  AWS_REGION               : "{{ .Values.global.AWS.REGION }}"
  AWS_ENDPOINT             : "{{ .Values.global.AWS.ENDPOINT }}"
  MONGO_USER               : "{{ .Values.global.db.MONGO_INITDB_ROOT_USERNAME }}"
  MONGO_PW                 : "{{ .Values.global.db.MONGO_INITDB_ROOT_PASSWORD }}"  
  MONGO_HOST               : "{{ .Values.global.db.MONGO_INITDB_HOST_OPEN }}"
  MONGO_DB_NAME            : "{{ .Values.global.db.MONGO_INITDB_DATABASE_NEW }}"
