kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "dasmongovapdb.fullname" . }}-vap-data-vcl
  labels:
    {{- include "dasmongovapdb.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.global.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
