apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dasnasamongo.fullname" . }}
  labels:
    {{- include "dasnasamongo.labels" . | nindent 4 }}
data:
  REFERENCE_HOST           : "{{ .Values.global.REFERENCE_HOST_NASA }}"
  STORAGE_DIR              : "{{ .Values.config.STORAGE_DIR }}"
  MONGO_HOST            : "{{ .Release.Name }}-{{ .Values.config.MONGO_HOST_NASA }}"
  MONGO_INITDB_ROOT_USERNAME: "{{ .Values.global.db.MONGO_INITDB_ROOT_USERNAME }}"
  MONGO_INITDB_ROOT_PASSWORD: "{{ .Values.global.db.MONGO_INITDB_ROOT_PASSWORD }}"
  MONGO_INITDB_DATABASE: "{{ .Values.global.db.MONGO_INITDB_DATABASE }}"
  AWS_ACCESS_KEY_ID        : "{{ .Values.global.AWS.SECRET_ID_NASA }}"
  AWS_SECRET_ACCESS_KEY    : "{{ .Values.global.AWS.SECRET_KEY_NASA }}"
  AWS_S3_ENDPOINT          : "{{ .Values.global.AWS.ENDPOINT_NASA }}"
  AWS_REGION               : "{{ .Values.global.AWS.REGION_NASA }}"
  GDAL_DISABLE_READDIR_ON_OPEN : "EMPTY_DIR"
  DATASETS_SPEC             : "{{ .Values.config.DATASETS_SPEC }}"
  INGESTION_LOG             : "{{ .Values.config.INGESTION_LOG }}"
  FAIL_INGESTION_LOG             : "{{ .Values.config.FAIL_INGESTION_LOG }}"
 
