apiVersion: v1
kind: Service
metadata:
  name: {{ include "dasmongodbnew.fullname" . }}
  labels:
    {{- include "dasmongodbnew.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    {{- include "dasmongodbnew.selectorLabels" . | nindent 4 }}
